if(NOT DEFINED INPUT_SPEC OR NOT DEFINED OUTPUT_HEADER OR NOT DEFINED OUTPUT_SOURCE)
  message(FATAL_ERROR "INPUT_SPEC, OUTPUT_HEADER, and OUTPUT_SOURCE are required")
endif()

file(READ "${INPUT_SPEC}" spec_content)
string(REPLACE "\r\n" "\n" spec_content "${spec_content}")
string(REPLACE "\r" "\n" spec_content "${spec_content}")
string(REPLACE "\n" ";" spec_lines "${spec_content}")

set(header_text "/* Auto-generated by GenerateEmbeddedAssets.cmake. */\n#ifndef FUSE_EMBEDDED_ASSETS_H\n#define FUSE_EMBEDDED_ASSETS_H\n\n#include \"utils.h\"\n\nint utils_read_embedded_asset( const char *filename, utils_file *file, utils_aux_type type );\n\n#endif\n")

set(source_text "/* Auto-generated by GenerateEmbeddedAssets.cmake. */\n#include <string.h>\n\n#include \"embedded_assets.h\"\n\ntypedef struct fuse_embedded_asset_entry {\n  const char *name;\n  utils_aux_type type;\n  const unsigned char *data;\n  size_t size;\n} fuse_embedded_asset_entry;\n\n")

set(entries_text "static const fuse_embedded_asset_entry fuse_embedded_assets[] = {\n")
set(asset_index 0)

foreach(spec_line IN LISTS spec_lines)
  if(spec_line STREQUAL "")
    continue()
  endif()

  string(REPLACE "|" ";" spec_fields "${spec_line}")
  list(LENGTH spec_fields spec_field_count)
  if(NOT spec_field_count EQUAL 3)
    message(FATAL_ERROR "Invalid asset specification line: ${spec_line}")
  endif()

  list(GET spec_fields 0 asset_type)
  list(GET spec_fields 1 asset_name)
  list(GET spec_fields 2 asset_path)

  if(asset_type STREQUAL "LIB")
    set(asset_type_enum "UTILS_AUXILIARY_LIB")
  elseif(asset_type STREQUAL "WIDGET")
    set(asset_type_enum "UTILS_AUXILIARY_WIDGET")
  else()
    message(FATAL_ERROR "Unknown asset type: ${asset_type}")
  endif()

  file(READ "${asset_path}" asset_hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1, " asset_bytes "${asset_hex}")

  set(array_name "fuse_embedded_asset_${asset_index}")
  string(APPEND source_text "static const unsigned char ${array_name}[] = { ${asset_bytes} };\n")
  string(APPEND entries_text "  { \"${asset_name}\", ${asset_type_enum}, ${array_name}, sizeof(${array_name}) },\n")
  math(EXPR asset_index "${asset_index} + 1")
endforeach()

string(APPEND entries_text "};\n\n")
string(APPEND source_text "${entries_text}")
string(APPEND source_text "int\nutils_read_embedded_asset( const char *filename, utils_file *file, utils_aux_type type )\n{\n  size_t i;\n\n  for( i = 0; i < sizeof( fuse_embedded_assets ) / sizeof( fuse_embedded_assets[0] ); i++ ) {\n    const fuse_embedded_asset_entry *asset = &fuse_embedded_assets[i];\n    if( asset->type != type ) continue;\n    if( strcmp( asset->name, filename ) != 0 ) continue;\n\n    file->length = asset->size;\n    file->buffer = libspectrum_new( unsigned char, file->length );\n    memcpy( file->buffer, asset->data, file->length );\n    return 0;\n  }\n\n  return -1;\n}\n")

file(WRITE "${OUTPUT_HEADER}" "${header_text}")
file(WRITE "${OUTPUT_SOURCE}" "${source_text}")